apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- base
commonLabels:
  app: todoapp
images:
- name: todoapp-backend
  newName: asia-southeast1-docker.pkg.dev/neat-motif-446107-p7/erpapp-repository/erpapp-backend
  newTag: v0.0.5
- name: todoapp-frontend
  newName: asia-northeast1-docker.pkg.dev/phu-le-it/todoapp-repository/todoapp-frontend
  newTag: v1.0.5
