apiVersion: v1
kind: Service # Service cung cấp một endpoint ổn định để truy cập các pod (backend pod trong trường hợp này)
metadata:
  name: backend-service # Tên của Service (phải là duy nhất trong namespace)
  labels:
    role: backend # Gán nhãn cho Service, thường dùng để dễ dàng quản lý hoặc tìm kiếm các tài nguyên
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-http-hc-config"}' # Annotation này liên kết Service với tài nguyên BackendConfig có tên backend-http-hc-config,  định cấu hình các thuộc tính bổ sung cho Load Balancer, như Health Check hoặc Timeout (được định nghĩa trong file BackendConfig trước đó).
spec:
  ports: # Xác định các port mà Service expose
  - port: 80 # Port mà Service lắng nghe (cổng bên ngoài)
    targetPort: 8080 # Port trên các backend pod mà lưu lượng sẽ được chuyển đến (ứng dụng backend của bạn lắng nghe trên cổng 8080).
    protocol: TCP
    name: http
  selector: # Selector đóng vai trò "nối" Service với các backend pod
    role: backend # Service sẽ chuyển lưu lượng đến các pod có nhãn role: backend
